- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3, virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando dependencias (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/' 
    - name: Alterar hosts do settings
      lineinfile:
        path: ~/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes

    - name: Iniciando o servico
      shell: '. /home/ubuntu/tcc/venv/bin/activate; cd /home/ubuntu/tcc/; python3 manage.py runserver 0.0.0.0:8000' 